# Generated by Django 4.1.7 on 2025-04-07 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingOperationJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15)),
                ('source', models.CharField(max_length=250, verbose_name='source/Consignor')),
                ('commodity', models.CharField(max_length=250, verbose_name='Location of Weighbridge')),
                ('wb_register_number', models.CharField(max_length=250, verbose_name='WB Register No')),
                ('rake', models.CharField(max_length=250, verbose_name='Rake No')),
                ('number_of_wagon', models.CharField(max_length=250, verbose_name='No Of Wagon')),
                ('gross_weight', models.CharField(max_length=250, verbose_name='Gross Weight in Tonnes')),
                ('net_weight', models.CharField(max_length=250, verbose_name='Net Weight in Tonnes')),
                ('rake_in_time', models.DateTimeField(verbose_name='Rake In Time')),
                ('system_one', models.TextField(verbose_name='System-1 /WB-1 status')),
                ('system_two', models.TextField(verbose_name='System-2 /WB-2 status')),
                ('general', models.TextField(verbose_name='General')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_operation_assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_operation_entry_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_operation_modify_by', to=settings.AUTH_USER_MODEL)),
                ('present_staffs', models.ManyToManyField(related_name='weighing_operation_present_staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeighingMaintenanceJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15)),
                ('complaint_time', models.DateTimeField()),
                ('complaint_nature', models.CharField(max_length=250, verbose_name='Nature/Details of Complaint')),
                ('weighbridge_location', models.CharField(max_length=250, verbose_name='Location of Weighbridge')),
                ('reported_by', models.TextField(verbose_name='Reported By/From')),
                ('action_taken', models.TextField(verbose_name='Action Taken')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_maintenance_assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_maintenance_entry_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighing_maintenance_modify_by', to=settings.AUTH_USER_MODEL)),
                ('present_staffs', models.ManyToManyField(related_name='weighing_maintenance_present_staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairLabJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15)),
                ('work_order_number', models.CharField(max_length=50)),
                ('work_order_receive_date', models.DateField()),
                ('work_order_completion_date', models.DateField()),
                ('department', models.CharField(db_index=True, max_length=250)),
                ('job_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('remarks', models.TextField()),
                ('information_given_department_date', models.DateField(null=True)),
                ('material_handover_department_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Beyond Repair', 'Beyond Repair'), ('Taken Back', 'Taken Back')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairlab_assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairlab_entry_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairlab_modify_by', to=settings.AUTH_USER_MODEL)),
                ('present_staffs', models.ManyToManyField(related_name='repairlab_present_staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PowerLabJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15)),
                ('work_order_number', models.CharField(max_length=50)),
                ('work_order_receive_date', models.DateField()),
                ('work_order_completion_date', models.DateField()),
                ('department', models.CharField(db_index=True, max_length=250)),
                ('job_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('remarks', models.TextField()),
                ('information_given_department_date', models.DateField(null=True)),
                ('material_handover_department_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Beyond Repair', 'Beyond Repair'), ('Taken Back', 'Taken Back')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerlab_assigned_staff', to=settings.AUTH_USER_MODEL)),
                ('entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerlab_entry_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='powerlab_modify_by', to=settings.AUTH_USER_MODEL)),
                ('present_staffs', models.ManyToManyField(related_name='powerlab_present_staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('department', models.CharField(db_index=True, max_length=250)),
                ('area', models.CharField(db_index=True, max_length=250)),
                ('job_start_time', models.DateTimeField()),
                ('job_completion_time', models.DateTimeField()),
                ('job_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('remarks', models.TextField()),
                ('persons', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_entry_by', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_modify_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
