# Generated by Django 4.1.7 on 2025-02-25 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedstock',
            name='is_lent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='perishable_product',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stocks',
            name='expired_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stockshistory',
            name='obsolete_inventory_barcode',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='history_type',
            field=models.CharField(choices=[('NEW MATERIAL', 'NEW MATERIAL'), ('RETURN MATERIAL', 'RETURN MATERIAL'), ('BORROWING MATERIAL', 'BORROWING MATERIAL'), ('RETURN BORROWED MATERIAL', 'RETURN BORROWED MATERIAL'), ('MATERIAL CONSUMPTION', 'MATERIAL CONSUMPTION'), ('LENDING MATERIAL', 'LENDING MATERIAL')], db_index=True, default='NEW MATERIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='is_stock_out',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
