# Generated by Django 4.1.7 on 2025-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_powerlabjob_is_save_draft_repairlabjob_is_save_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='complaint_nature',
            field=models.CharField(choices=[('leakage', 'Water Leakage'), ('power_outage', 'Power Outage'), ('ac_issue', 'Air Conditioner Issue'), ('plumbing', 'Plumbing Problem'), ('cleaning', 'Cleaning Request'), ('internet', 'Internet Not Working'), ('other', 'Other (please specify)')], max_length=250, verbose_name='Nature/Details of Complaint'),
        ),
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='weighbridge_location',
            field=models.CharField(choices=[('gate_1', 'Gate 1'), ('gate_2', 'Gate 2'), ('yard_area', 'Yard Area'), ('loading_bay', 'Loading Bay'), ('admin_block', 'Admin Block'), ('other', 'Other (please specify)')], max_length=250, verbose_name='Location of Weighbridge'),
        ),
    ]
