# Generated by Django 4.1.7 on 2025-04-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_alter_weighingmaintenancejob_complaint_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingoperationjob',
            name='commodity',
            field=models.CharField(choices=[('iron', 'Iron'), ('steel', 'Steel'), ('copper', 'Copper'), ('aluminum', 'Aluminum')], max_length=250, verbose_name='Location of Weighbridge'),
        ),
        migrations.AlterField(
            model_name='weighingoperationjob',
            name='source',
            field=models.CharField(choices=[('vendor1', 'Vendor 1'), ('vendor2', 'Vendor 2'), ('vendor3', 'Vendor 3')], max_length=250, verbose_name='source/Consignor'),
        ),
    ]
