# Generated by Django 4.1.7 on 2025-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_weighingoperationjob_commodity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='complaint_nature',
            field=models.CharField(choices=[('Water Leakage', 'Water Leakage'), ('Power Outage', 'Power Outage'), ('Air Conditioner Issue', 'Air Conditioner Issue'), ('Plumbing Problem', 'Plumbing Problem'), ('Cleaning Reques', 'Cleaning Request'), ('Internet Not Working', 'Internet Not Working'), ('Other (please specify)', 'Other (please specify)')], max_length=250, verbose_name='Nature/Details of Complaint'),
        ),
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='weighbridge_location',
            field=models.CharField(choices=[('Gate 1', 'Gate 1'), ('Gate 2', 'Gate 2'), ('Yard Area', 'Yard Area'), ('Loading Bay', 'Loading Bay'), ('Admin Block', 'Admin Block'), ('Other (please specify)', 'Other (please specify)')], max_length=250, verbose_name='Location of Weighbridge'),
        ),
    ]
