# Generated by Django 4.1.7 on 2025-03-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_remove_borrowedstock_is_lent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='personnel_number',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
