# Generated by Django 4.1.7 on 2025-05-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_employees_personnel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.barcodes'),
        ),
    ]
