# Generated by Django 4.1.7 on 2025-04-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_alter_weighingoperationjob_commodity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerlabjob',
            name='information_given_department_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='material_handover_department_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='work_order_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='work_order_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
