# Generated by Django 4.1.7 on 2025-07-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_products_is_active_alter_stocks_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='AdminApp.products'),
        ),
    ]
