# Generated by Django 4.1.7 on 2025-04-17 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0009_automationjob_date_automationjob_present_staffs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationjob',
            name='date',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='present_staffs',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='supporting_staff',
        ),
        migrations.AddField(
            model_name='cctvjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 17, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cctvjob',
            name='entry_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cctv_entry_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cctvjob',
            name='modify_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cctv_modify_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cctvjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
