# Generated by Django 4.1.7 on 2025-07-23 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0010_stockshistory_source_alter_stocks_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('reference_no', models.CharField(db_index=True, help_text='SAP PR No', max_length=100)),
                ('fulfillment_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('PARTIALLY_CANCELLED', 'Partially Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for requisition status change', null=True)),
                ('total_material', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('reservation_type', models.CharField(choices=[('SAP', 'SAP'), ('T72', 'T72')], max_length=17)),
                ('reference_no', models.CharField(db_index=True, help_text='PO nummbe or T72 number or Cash Purchase', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for requisition status change', null=True)),
                ('total_material', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockshistory',
            name='reference_no',
            field=models.CharField(db_index=True, help_text='PO No. or T72 number or PR No.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='history_type',
            field=models.CharField(choices=[('NEW MATERIAL', 'NEW MATERIAL'), ('RETURN MATERIAL', 'RETURN MATERIAL'), ('RECEIVE LENT MATERIAL', 'RECEIVE LENT MATERIAL'), ('BORROWING MATERIAL', 'BORROWING MATERIAL'), ('RESERVATION', 'RESERVATION'), ('RETURN BORROWED MATERIAL', 'RETURN BORROWED MATERIAL'), ('MATERIAL CONSUMPTION', 'MATERIAL CONSUMPTION'), ('LENDING MATERIAL', 'LENDING MATERIAL'), ('REQUISITION', 'REQUISITION')], db_index=True, default='NEW MATERIAL', max_length=30),
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.products')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminApp.reservation')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.source')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('requested_quantity', models.FloatField()),
                ('fulfilled_quantity', models.FloatField(default=0)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('purpose', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.products')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminApp.requisition')),
            ],
        ),
    ]
