# Generated by Django 4.1.7 on 2025-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_remove_automationjob_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='complaint_nature',
            field=models.CharField(choices=[('INSPECTION OF WBS', 'INSPECTION OF WBS'), ('PREVENTIVE MAINTENANCE OF WBS', 'PREVENTIVE MAINTENANCE OF WBS'), ('CALIBRATION CHECKING OF WBS', 'CALIBRATION CHECKING OF WBS'), ('PRE-STAMPING CHECKING OF WBS', 'PRE-STAMPING CHECKING OF WBS'), ('VERIFICATION & STAMPING OF WBS', 'VERIFICATION & STAMPING OF WBS'), ('SERVICE SUPPORT', 'SERVICE SUPPORT'), ('OTHERS', 'OTHERS')], max_length=250, verbose_name='Nature/Details of Complaint'),
        ),
    ]
