# Generated by Django 4.1.7 on 2025-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_alter_weighingmaintenancejob_complaint_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvjob',
            name='complain_nature',
            field=models.TextField(choices=[('INSPECTION OF WBS', 'INSPECTION OF WBS'), ('PREVENTIVE MAINTENANCE OF WBS', 'PREVENTIVE MAINTENANCE OF WBS'), ('CALIBRATION CHECKING OF WBS', 'CALIBRATION CHECKING OF WBS'), ('PRE-STAMPING CHECKING OF WBS', 'PRE-STAMPING CHECKING OF WBS'), ('VERIFICATION & STAMPING OF WBS', 'VERIFICATION & STAMPING OF WBS'), ('SERVICE SUPPORT', 'SERVICE SUPPORT'), ('OTHERS', 'OTHERS')], verbose_name='Nature of Complain'),
        ),
    ]
