# Generated by Django 4.1.7 on 2026-01-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0011_requisition_reservation_stockshistory_reference_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T72Purchase',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('receive_date', models.DateField()),
                ('daybook_number', models.CharField(max_length=50, unique=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('party_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('ISSUED', 'Issued')], default='RECEIVED', max_length=20)),
                ('used_area', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t72_authorized', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t72_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='shoe_size',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='T72PurchaseItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Order Quantity', max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, help_text='Available Quantity', max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminApp.t72purchase')),
            ],
            options={
                'unique_together': {('purchase', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='T72ItemIssuedHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_at', models.DateField(auto_now_add=True)),
                ('issue_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_history', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_history', to='AdminApp.t72purchaseitem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_history', to='AdminApp.t72purchase')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_history', to='AdminApp.employees')),
            ],
        ),
    ]
