# Generated by Django 4.1.7 on 2025-04-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_alter_cctvjob_complain_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvjob',
            name='complain_nature',
            field=models.TextField(choices=[('PM', 'PM'), ('BREAKDOWN', 'BREAKDOWN'), ('RELOCATION', 'RELOCATION'), ('DISMANTLING', 'DISMANTLING'), ('NEW INSTALLATION', 'NEW INSTALLATION'), ('OTHERS', 'OTHERS')], verbose_name='Nature of Complain'),
        ),
    ]
