# Generated by Django 4.1.7 on 2025-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_alter_cctvjob_complain_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationjob',
            name='department',
            field=models.CharField(choices=[('AC', 'AC'), ('BFs', 'BFs'), ('CCD', 'CCD'), ('CED', 'CED'), ('CES', 'CES'), ('COKE OVENs', 'COKE OVENs'), ('CP-2', 'CP-2'), ('CPP-1', 'CPP-1'), ('DESIGN', 'DESIGN'), ('HRDC', 'HRDC'), ('HSM-2', 'HSM-2'), ('I&A (INSTRUMENTATION)', 'I&A (INSTRUMENTATION)'), ('LDBP', 'LDBP'), ('Mines (BIM,BOM,KIM)', 'Mines (BIM,BOM,KIM)'), ('NPM', 'NPM'), ('PD', 'PD'), ('PIPE PLANTs', 'PIPE PLANTs'), ('PM', 'PM'), ('R&C LAB', 'R&C LAB'), ('RMHP', 'RMHP'), ('Roll shop', 'Roll shop'), ('RS (E)', 'RS (E)'), ('SHOPs', 'SHOPs'), ('SMS-1', 'SMS-1'), ('SMS-2', 'SMS-2'), ('SP-1', 'SP-1'), ('SP-2', 'SP-2'), ('SP-3', 'SP-3'), ('SPP', 'SPP'), ('SSM', 'SSM'), ('TOP-2', 'TOP-2'), ('Town Engg (E)', 'Town Engg (E)'), ('Transport & FMM', 'Transport & FMM'), ('TRM', 'TRM'), ('WMD', 'WMD')], db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cctvjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('c Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='department',
            field=models.CharField(choices=[('AC', 'AC'), ('BFs', 'BFs'), ('CCD', 'CCD'), ('CED', 'CED'), ('CES', 'CES'), ('COKE OVENs', 'COKE OVENs'), ('CP-2', 'CP-2'), ('CPP-1', 'CPP-1'), ('DESIGN', 'DESIGN'), ('HRDC', 'HRDC'), ('HSM-2', 'HSM-2'), ('I&A (INSTRUMENTATION)', 'I&A (INSTRUMENTATION)'), ('LDBP', 'LDBP'), ('Mines (BIM,BOM,KIM)', 'Mines (BIM,BOM,KIM)'), ('NPM', 'NPM'), ('PD', 'PD'), ('PIPE PLANTs', 'PIPE PLANTs'), ('PM', 'PM'), ('R&C LAB', 'R&C LAB'), ('RMHP', 'RMHP'), ('Roll shop', 'Roll shop'), ('RS (E)', 'RS (E)'), ('SHOPs', 'SHOPs'), ('SMS-1', 'SMS-1'), ('SMS-2', 'SMS-2'), ('SP-1', 'SP-1'), ('SP-2', 'SP-2'), ('SP-3', 'SP-3'), ('SPP', 'SPP'), ('SSM', 'SSM'), ('TOP-2', 'TOP-2'), ('Town Engg (E)', 'Town Engg (E)'), ('Transport & FMM', 'Transport & FMM'), ('TRM', 'TRM'), ('WMD', 'WMD')], db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('c Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='repairlabjob',
            name='department',
            field=models.CharField(choices=[('AC', 'AC'), ('BFs', 'BFs'), ('CCD', 'CCD'), ('CED', 'CED'), ('CES', 'CES'), ('COKE OVENs', 'COKE OVENs'), ('CP-2', 'CP-2'), ('CPP-1', 'CPP-1'), ('DESIGN', 'DESIGN'), ('HRDC', 'HRDC'), ('HSM-2', 'HSM-2'), ('I&A (INSTRUMENTATION)', 'I&A (INSTRUMENTATION)'), ('LDBP', 'LDBP'), ('Mines (BIM,BOM,KIM)', 'Mines (BIM,BOM,KIM)'), ('NPM', 'NPM'), ('PD', 'PD'), ('PIPE PLANTs', 'PIPE PLANTs'), ('PM', 'PM'), ('R&C LAB', 'R&C LAB'), ('RMHP', 'RMHP'), ('Roll shop', 'Roll shop'), ('RS (E)', 'RS (E)'), ('SHOPs', 'SHOPs'), ('SMS-1', 'SMS-1'), ('SMS-2', 'SMS-2'), ('SP-1', 'SP-1'), ('SP-2', 'SP-2'), ('SP-3', 'SP-3'), ('SPP', 'SPP'), ('SSM', 'SSM'), ('TOP-2', 'TOP-2'), ('Town Engg (E)', 'Town Engg (E)'), ('Transport & FMM', 'Transport & FMM'), ('TRM', 'TRM'), ('WMD', 'WMD')], db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='repairlabjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('c Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='complaint_nature',
            field=models.CharField(choices=[('INSPECTION OF WBS', 'INSPECTION OF WBS'), ('PREVENTIVE MAINTENANCE OF WBS', 'PREVENTIVE MAINTENANCE OF WBS'), ('CALIBRATION CHECKING OF WBS', 'CALIBRATION CHECKING OF WBS'), ('PRE-STAMPING CHECKING OF WBS', 'PRE-STAMPING CHECKING OF WBS'), ('VERIFICATION & STAMPING OF WBS', 'VERIFICATION & STAMPING OF WBS'), ('SERVICE SUPPORT', 'SERVICE SUPPORT')], max_length=250, verbose_name='Nature/Details of Complaint'),
        ),
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('c Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='weighbridge_location',
            field=models.CharField(choices=[('20T M-17 SWPP PF WB', '20T M-17 SWPP PF WB'), ('AB-BAY STATIC RAIL WB PF-A/B/C', 'AB-BAY STATIC RAIL WB PF-A/B/C'), ('BC-BAY STATIC RAIL WB PF-A/B/C', 'BC-BAY STATIC RAIL WB PF-A/B/C'), ('CD-BAY STATIC RAIL WB', 'CD-BAY STATIC RAIL WB'), ('CEMENT STORE 40T ROAD WB', 'CEMENT STORE 40T ROAD WB'), ('CRM 30T RS-BAY(SHIPPING) PF WB', 'CRM 30T RS-BAY(SHIPPING) PF WB'), ('GRILL GATE 150T RAIL I/M WB LINE#241', 'GRILL GATE 150T RAIL I/M WB LINE#241'), ('GRILL GATE 150T RAIL I/M WB LINE#243', 'GRILL GATE 150T RAIL I/M WB LINE#243'), ('HK GATE(NEW) 40T ROAD WB', 'HK GATE(NEW) 40T ROAD WB'), ('HK GATE(OLD) 50T ROAD WB', 'HK GATE(OLD) 50T ROAD WB'), ('HM 200T STATIC RAIL WB PCM LINE', 'HM 200T STATIC RAIL WB PCM LINE'), ('HM 250T STATIC RAIL WB PF-A', 'HM 250T STATIC RAIL WB PF-A'), ('HM 250T STATIC RAIL WB PF-B', 'HM 250T STATIC RAIL WB PF-B'), ('HM 800T STATIC RAIL WB LINE#1 WB-1 & WB-2', 'HM 800T STATIC RAIL WB LINE#1 WB-1 & WB-2'), ('HM 800T STATIC RAIL WB LINE#2 WB-1 & WB-2', 'HM 800T STATIC RAIL WB LINE#2 WB-1 & WB-2'), ('HSM-1 30T NEW DIVIDING LINE PF WB', 'HSM-1 30T NEW DIVIDING LINE PF WB'), ('HSM-2 COIL CONVEYER WEIGHING SYS.', 'HSM-2 COIL CONVEYER WEIGHING SYS.'), ('HSM-2 COIL YARD PF WB-1', 'HSM-2 COIL YARD PF WB-1'), ('HSM-2 COIL YARD PF WB-2', 'HSM-2 COIL YARD PF WB-2'), ('HSM-2 SSL PF WB-3', 'HSM-2 SSL PF WB-3'), ('NCCY 140T RAIL I/M WB', 'NCCY 140T RAIL I/M WB'), ('NEW SGP GATE 100T ROAD WB', 'NEW SGP GATE 100T ROAD WB'), ('NEW TARAPUR GATE 100T ROAD WB', 'NEW TARAPUR GATE 100T ROAD WB'), ('NPM 100T ROAD WB-1', 'NPM 100T ROAD WB-1'), ('NPM 100T ROAD WB-2', 'NPM 100T ROAD WB-2'), ('NPM STATIC RAIL WB PF-A/B/C', 'NPM STATIC RAIL WB PF-A/B/C'), ('RECEPTION YARD 150T RAIL I/M WB-1', 'RECEPTION YARD 150T RAIL I/M WB-1'), ('RECEPTION YARD 150T RAIL I/M WB-2', 'RECEPTION YARD 150T RAIL I/M WB-2'), ('SSD 100T ROAD WB', 'SSD 100T ROAD WB'), ('SSD 140T RAIL I/M WB', 'SSD 140T RAIL I/M WB'), ('SSM 20T HJ-BAY PF WB', 'SSM 20T HJ-BAY PF WB'), ('SSM 20T JK-BAY PF WB', 'SSM 20T JK-BAY PF WB'), ('SSSY 100T ROAD WB', 'SSSY 100T ROAD WB'), ('SSSY 60T ROAD WB', 'SSSY 60T ROAD WB')], max_length=250, verbose_name='Location of Weighbridge'),
        ),
        migrations.AlterField(
            model_name='weighingoperationjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('c Shift', 'C SHIFT')], max_length=15),
        ),
    ]
