# Generated by Django 4.1.7 on 2025-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0014_alter_automationjob_department_alter_cctvjob_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='powerlabjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='repairlabjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='weighingmaintenancejob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='weighingoperationjob',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'GENERAL SHIFT'), ('A Shift', 'A SHIFT'), ('B Shift', 'B SHIFT'), ('C Shift', 'C SHIFT')], max_length=15),
        ),
    ]
