# Generated by Django 4.1.7 on 2025-10-23 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0015_alter_cctvjob_shift_alter_powerlabjob_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='slideshow_images/')),
                ('display_until', models.DateField(blank=True, help_text='Date until which the image should be displayed. If null, it displays indefinitely.', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_slides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
