# Generated by Django 4.2.10 on 2024-04-24 11:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SIApp', '0002_compliance_created_at_sir_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='archive_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compliance',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sir',
            name='archive_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sir',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sir',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stabilitycertification',
            name='archive_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stabilitycertification',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stabilitycertification',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StabilityCertificationLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('View Stability Certification', 'VIEW'), ('Add Stability Certification', 'ADD'), ('Update Stability Certification', 'UPDATE'), ('Archive Stability Certification', 'ARCHIVE'), ('Delete Stability Certification', 'DELETE')], default='View Stability Certification', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('stability_certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIApp.stabilitycertification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SIRLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('View SIR', 'VIEW'), ('Add SIR', 'ADD'), ('Update SIR', 'UPDATE'), ('Archive SIR', 'ARCHIVE'), ('Delete SIR', 'DELETE')], default='View SIR', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('sir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIApp.sir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('View Compliance', 'VIEW'), ('Add Compliance', 'ADD'), ('Update Compliance', 'UPDATE'), ('Archive Compliance', 'ARCHIVE'), ('Delete Compliance', 'DELETE')], default='View Compliance', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('compliance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIApp.compliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
