# Generated by Django 4.2.10 on 2024-04-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0003_compliance_archive_reason_compliance_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stabilitycertificationlog',
            name='status',
            field=models.CharField(choices=[('View Stability Certificate', 'VIEW'), ('Add Stability Certificatie', 'ADD'), ('Update Stability Certificatie', 'UPDATE'), ('Archive Stability Certificatie', 'ARCHIVE'), ('Delete Stability Certificatie', 'DELETE')], default='View Stability Certificate', max_length=50),
        ),
    ]
