# Generated by Django 4.2.10 on 2024-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0004_alter_stabilitycertificationlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sir',
            name='title',
        ),
        migrations.AddField(
            model_name='sir',
            name='compliance',
            field=models.CharField(default='YES', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sir',
            name='year_of_inspection',
            field=models.CharField(default='2024', max_length=4),
            preserve_default=False,
        ),
    ]
