# Generated by Django 4.2.10 on 2024-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0005_remove_sir_title_sir_compliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sir',
            name='year_of_inspection',
            field=models.CharField(max_length=10),
        ),
    ]
