# Generated by Django 4.2.10 on 2024-04-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthApp', '0007_alter_subvolume_sub_volume_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StabilityCertification',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='stabilitycertification/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.department')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SIR',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('sir_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('attachment', models.FileField(upload_to='sir/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.department')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to='compliance/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.department')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.unit')),
            ],
        ),
    ]
