# Generated by Django 4.2.10 on 2024-07-02 11:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SIApp', '0006_alter_sir_year_of_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='document/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_archive', models.BooleanField(default=False)),
                ('archive_reason', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('View Compliance', 'VIEW'), ('Add Compliance', 'ADD'), ('Update Compliance', 'UPDATE'), ('Archive Compliance', 'ARCHIVE'), ('Delete Compliance', 'DELETE')], default='View Compliance', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIApp.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
