# Generated by Django 4.2.10 on 2024-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0008_alter_documentlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sir',
            name='agency',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='stabilitycertification',
            name='agency',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
