# Generated by Django 4.2.10 on 2024-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
