# Generated by Django 4.2.10 on 2024-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0003_alter_notice_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='media',
            field=models.FileField(default='', upload_to='slider/'),
            preserve_default=False,
        ),
    ]
