# Generated by Django 4.2.10 on 2024-04-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0002_rsnvolume_rsngroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsngroup',
            name='rsn_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApp.rsnvolume'),
        ),
    ]
