# Generated by Django 4.2.10 on 2024-04-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0008_alter_standard_document_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='title_of_standard',
        ),
        migrations.AlterField(
            model_name='standard',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
