# Generated by Django 4.2.10 on 2024-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0019_rsngroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsstitle',
            name='title_id',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
