# Generated by Django 4.2.10 on 2024-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0003_alter_rsngroup_rsn_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsngroup',
            name='group_no',
            field=models.CharField(max_length=100),
        ),
    ]
