# Generated by Django 4.2.10 on 2024-04-10 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0014_standardlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='standard',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standard',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standard',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='standardlog',
            name='status',
            field=models.CharField(choices=[('View Standard', 'VIEW'), ('Add Standard', 'ADD'), ('Update Standard', 'UPDATE'), ('Archive Standard', 'ARCHIVE')], default='View Standard', max_length=20),
        ),
    ]
