# Generated by Django 4.2.10 on 2024-04-23 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sir',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stabilitycertification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
