# Generated by Django 4.1.7 on 2025-04-07 16:09

import AuthApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Executive', 'Executive'), ('Area Incharge', 'Area Incharge'), ('Shift Incharge', 'Shift Incharge')], default='Admin', max_length=15)),
                ('personnel_number', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.JSONField(default=AuthApp.models.default_area)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogInOutLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('device_info', models.TextField(null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
