# Generated by Django 4.2.10 on 2024-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_type', models.CharField(choices=[('MANUALS', 'MANUALS'), ('REFERENCE BOOK', 'REFERENCE BOOK'), ('TENDER DOCUMENT', 'TENDER DOCUMENT'), ('CATALOUGE', 'CATALOUGE'), ('TECHNICAL CALCULATION', 'TECHNICAL CALCULATION'), ('TECHNICAL SPECIFICATION', 'TECHNICAL SPECIFICATION'), ('TECHNICAL REPORT', 'TECHNICAL REPORT'), ('PROJECT REPORT', 'PROJECT REPORT')], default='MANUALS', max_length=100)),
                ('manual_no', models.CharField(choices=[('MANUAL NO', 'MANUAL NO'), ('BOOK NO', 'BOOK NO'), ('TENDER DOCUMENT NO', 'TENDER DOCUMENT NO'), ('CATALOUGE NO', 'CATALOUGE NO'), ('TECHNICAL CALCULATION NO', 'TECHNICAL CALCULATION NO'), ('TECHNICAL SPECIFICATION NO', 'TECHNICAL SPECIFICATION NO'), ('TECHNICAL REPORT NO', 'TECHNICAL REPORT NO'), ('PROJECT REPORT NO', 'PROJECT REPORT NO')], db_index=True, default='MANUAL NO', max_length=100)),
                ('department', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('supplier', models.CharField(max_length=250, null=True)),
                ('package_no', models.CharField(max_length=100, null=True)),
                ('letter_no', models.CharField(max_length=100, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('upload_file', models.FileField(null=True, upload_to='')),
                ('editor', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('capacity', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
