# Generated by Django 4.2.10 on 2024-04-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0006_user_is_view_manual_user_is_view_standard'),
        ('ManualApp', '0002_alter_manual_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.unit'),
        ),
    ]
