# Generated by Django 4.2.10 on 2024-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0006_alter_manual_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
