# Generated by Django 4.2.10 on 2024-04-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0009_manual_created_at_manual_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='archive_reason',
            field=models.TextField(null=True),
        ),
    ]
