# Generated by Django 4.2.10 on 2024-04-10 15:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManualApp', '0010_manual_archive_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('View Manual', 'VIEW'), ('Add Manual', 'ADD'), ('Update Manual', 'UPDATE'), ('Archive Manual', 'ARCHIVE')], default='View Manual', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('manual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManualApp.manual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
