# Generated by Django 4.2.10 on 2024-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0011_manuallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuallog',
            name='status',
            field=models.CharField(choices=[('View Manual', 'VIEW'), ('Add Manual', 'ADD'), ('Update Manual', 'UPDATE'), ('Archive Manual', 'ARCHIVE'), ('Delete Manual', 'DELETE')], default='View Manual', max_length=20),
        ),
    ]
