# Generated by Django 4.2.10 on 2024-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0012_alter_manuallog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuallog',
            name='status',
            field=models.CharField(choices=[('View Document', 'VIEW'), ('Add Document', 'ADD'), ('Update Document', 'UPDATE'), ('Archive Document', 'ARCHIVE'), ('Delete Document', 'DELETE')], default='View Document', max_length=20),
        ),
    ]
