# Generated by Django 4.2.10 on 2024-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0013_alter_manuallog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='manual_no_numeric',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
