# Generated by Django 4.2.10 on 2024-06-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0014_manual_manual_no_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='dwg_zip_file',
            field=models.FileField(null=True, upload_to='manual/'),
        ),
        migrations.AddField(
            model_name='manual',
            name='file_type',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='manual_type',
            field=models.CharField(choices=[('MANUALS', 'MANUALS'), ('REFERENCE BOOK', 'REFERENCE BOOK'), ('TENDER DOCUMENT', 'TENDER DOCUMENT'), ('CATALOUGE', 'CATALOUGE'), ('TECHNICAL CALCULATION', 'TECHNICAL CALCULATION'), ('TECHNICAL SPECIFICATION', 'TECHNICAL SPECIFICATION'), ('TECHNICAL REPORT', 'TECHNICAL REPORT'), ('PROJECT REPORT', 'PROJECT REPORT'), ('PROJECT SUBMITTED DRAWINGS', 'PROJECT SUBMITTED DRAWINGS')], default='MANUALS', max_length=100),
        ),
    ]
