# Generated by Django 4.2.10 on 2024-06-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0015_manual_dwg_zip_file_manual_file_type_manual_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='dwg_zip_file',
        ),
    ]
