# Generated by Django 4.2.10 on 2024-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0003_alter_manual_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='registration_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
