# Generated by Django 4.2.10 on 2024-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0004_alter_manual_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='manual_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
