# Generated by Django 4.2.10 on 2024-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0005_alter_manual_manual_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
