# Generated by Django 4.2.10 on 2024-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0007_alter_manual_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='upload_file',
            field=models.FileField(null=True, upload_to='manual/'),
        ),
    ]
