# Generated by Django 4.2.10 on 2024-04-10 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManualApp', '0008_alter_manual_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='manual',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manual',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manual',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
