# Generated by Django 4.2.10 on 2024-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_volume_subvolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_view_layout',
            field=models.BooleanField(default=True),
        ),
    ]
