# Generated by Django 4.2.10 on 2024-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0008_user_is_disable_dwg_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photo/'),
        ),
    ]
