# Generated by Django 4.2.10 on 2024-05-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0009_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_design_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_view_technical_calculation',
            field=models.BooleanField(default=True),
        ),
    ]
