# Generated by Django 4.2.10 on 2024-06-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0011_alter_user_personnel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
