# Generated by Django 4.2.10 on 2024-06-10 18:29

import AuthApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0012_remove_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_design_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_disable_dwg_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_download_drawing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_view_manual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_view_layout',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_view_standard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_view_technical_calculation',
        ),
        migrations.AddField(
            model_name='user',
            name='document_permission',
            field=models.JSONField(default=AuthApp.models.default_document_permission),
        ),
        migrations.AddField(
            model_name='user',
            name='drawing_permission',
            field=models.JSONField(default=AuthApp.models.default_drawing_permission),
        ),
        migrations.AddField(
            model_name='user',
            name='standard_permission',
            field=models.JSONField(default=AuthApp.models.default_standard_permission),
        ),
    ]
