# Generated by Django 4.1.7 on 2025-02-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_borrowedstock_is_lent_products_perishable_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedstock',
            old_name='net_quantity',
            new_name='borrowed_quantity',
        ),
        migrations.AddField(
            model_name='borrowedstock',
            name='lent_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='history_type',
            field=models.CharField(choices=[('NEW MATERIAL', 'NEW MATERIAL'), ('RETURN MATERIAL', 'RETURN MATERIAL'), ('RETURN LENT MATERIAL', 'RETURN LENT MATERIAL'), ('BORROWING MATERIAL', 'BORROWING MATERIAL'), ('RETURN BORROWED MATERIAL', 'RETURN BORROWED MATERIAL'), ('MATERIAL CONSUMPTION', 'MATERIAL CONSUMPTION'), ('LENDING MATERIAL', 'LENDING MATERIAL')], db_index=True, default='NEW MATERIAL', max_length=30),
        ),
    ]
