# Generated by Django 4.1.7 on 2025-07-10 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_alter_stocks_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockshistory',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.source'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.source'),
        ),
    ]
