from django.urls import path
from AdminApp import views

urlpatterns = [
    path("dashboard", views.DashboardApiView.as_view()),
    path("login_log_graph", views.DashboardLogInGraphView.as_view()),
    path("drawing_log_graph", views.DashboardDrawingLogGraphView.as_view()),
    path("standard_log_graph", views.DashboardStandardLogGraphView.as_view()),
    path("manual_log_graph", views.DashboardManualLogGraphView.as_view()),
    path("si_log_graph", views.DashboardSILogGraphView.as_view()),
    path("visitor_count", views.VisitorCountApiView.as_view()),
    path("total_user", views.TotalUserApiView.as_view()),
    path("user", views.UserApiView.as_view()),
    path("user/<str:id>", views.UserApiView.as_view()),
    path("user_status_update", views.UserStatusUpadteApiView.as_view()),
    path("user_change_password", views.UserChangePasswordApiView.as_view()),
    path("user_drawing_log", views.UserDrawingLogApiView.as_view()),
    path("user_drawing_log/<str:user_id>", views.UserDrawingLogApiView.as_view()),
    path("user_standard_log", views.UserStandardLogApiView.as_view()),
    path("user_standard_log/<str:user_id>", views.UserStandardLogApiView.as_view()),
    path("user_manual_log", views.UserManualLogApiView.as_view()),
    path("user_manual_log/<str:user_id>", views.UserManualLogApiView.as_view()),
    path("user_sir_log", views.UserSIRLogApiView.as_view()),
    path("user_sir_log/<str:user_id>", views.UserSIRLogApiView.as_view()),
    path("user_stability_certificate_log", views.UserStabilityCertificateLogApiView.as_view()),
    path("user_stability_certificate_log/<str:user_id>", views.UserStabilityCertificateLogApiView.as_view()),
    path("user_compliance_log", views.UserComplianceLogApiView.as_view()),
    path("user_compliance_log/<str:user_id>", views.UserComplianceLogApiView.as_view()),
    path("user_login_activity", views.UserLogInLogoutLogApiView.as_view()),
    path("user_login_activity/<str:user_id>", views.UserLogInLogoutLogApiView.as_view()),
    path("department", views.DepartmentApiView.as_view()),
    path("department/<str:id>", views.UserApiView.as_view()),
    path("unit", views.UnitApiView.as_view()),
    path("unit/<str:id>", views.UnitApiView.as_view()),
    path("rs_volume", views.RSVolumeApiView.as_view()),
    path("rs_sub_volume", views.RSSubVolumeApiView.as_view()),
    path("search/unit", views.SearchUnitApiView.as_view()),
    path("search/department", views.SearchDepartmentApiView.as_view()),
    path("search/rs_sub_volume", views.SearchSubVolumeApiView.as_view()),
    path("search/rs_volume", views.SearchRSVolumeApiView.as_view()),
    path("search/user", views.SearchUserApiView.as_view()),
    path("export_data", views.ExportDataExcelApiView.as_view()),

]
