# Generated by Django 4.1.7 on 2024-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_remove_employees_email_employees_personnel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='net_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockshistory',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
