from django.urls import path

from .views import (
    SirApiView,
    ArchiveSIRApiView,
    ApproveSIRApiView,
    SIRLogApiView,
    DownloadSIRLogExcelApiView,
    BulkArchiveSIRApiView,
    DownloadSIRFileApiView,
    SIRPermanentDeleteApiView,
    
    StabilityCertificationApiView,
    DownloadStabilityCertificationFileApiView,
    StabilityCertificationLogApiView,
    ApproveStabilityCertificationApiView,
    ArchiveStabilityCertificationApiView,
    DownloadStabilityCertificationLogExcelApiView,
    BulkArchiveStabilityCertificationApiView,
    StabilityCertificationPermanentDeleteApiView,
    
    ComplianceApiView,
    ArchiveComplianceApiView,
    ApproveComplianceApiView,
    ComplianceLogApiView,
    DownloadComplianceFileApiView,
    DownloadComplianceLogExcelApiView,
    BulkArchiveComplianceApiView,
    CompliancePermanentDeleteApiView,
    )


urlpatterns = [
    path('sir', SirApiView.as_view()),
    path('sir/<str:id>', SirApiView.as_view()),
    path('sir_file_download/<str:id>', DownloadSIRFileApiView.as_view()),
    path('sir_archive', ArchiveSIRApiView.as_view()),
    path('sir_approve', ApproveSIRApiView.as_view()),
    path('sir_log', SIRLogApiView.as_view()),
    path('sir_log/<str:sir_id>', SIRLogApiView.as_view()),
    path('download_sir_log_excel', DownloadSIRLogExcelApiView.as_view()),
    path('sir_bulk_archive', BulkArchiveSIRApiView.as_view()),
    path('sir_permanent_delete', SIRPermanentDeleteApiView.as_view()),

    path('stability_certificate', StabilityCertificationApiView.as_view()),
    path('stability_certificate/<str:id>', StabilityCertificationApiView.as_view()),
    path('stability_certificate_file_download/<str:id>', DownloadStabilityCertificationFileApiView.as_view()),
    path('stability_certificate_log', StabilityCertificationLogApiView.as_view()),
    path('stability_certificate_log/<str:sc_id>', StabilityCertificationLogApiView.as_view()),
    path('stability_certificate_approve', ApproveStabilityCertificationApiView.as_view()),
    path('stability_certificate_archive', ArchiveStabilityCertificationApiView.as_view()),
    path('download_stability_certificate_log_excel', DownloadStabilityCertificationLogExcelApiView.as_view()),
    path('stability_certificate_bulk_archive', BulkArchiveStabilityCertificationApiView.as_view()),
    path('stability_certificate_permanent_delete', StabilityCertificationPermanentDeleteApiView.as_view()),
    
    path('compliance', ComplianceApiView.as_view()),
    path('compliance/<str:id>', ComplianceApiView.as_view()),
    path('compliance_archive', ArchiveComplianceApiView.as_view()),
    path('compliance_approve', ApproveComplianceApiView.as_view()),
    path('compliance_log', ComplianceLogApiView.as_view()),
    path('compliance_log/<str:com_id>', ComplianceLogApiView.as_view()),
    path('compliance_file_download/<str:id>', DownloadComplianceFileApiView.as_view()),
    path('download_compliance_log_excel', DownloadComplianceLogExcelApiView.as_view()),
    path('compliance_bulk_archive', BulkArchiveComplianceApiView.as_view()),
    path('compliance_permanent_delete', CompliancePermanentDeleteApiView.as_view()),
]