# Generated by Django 4.2.10 on 2024-03-27 17:02

import DrawingApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_volume_subvolume'),
        ('DrawingApp', '0003_drawing_is_archive_drawinglog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='volume',
        ),
        migrations.AddField(
            model_name='drawing',
            name='archive_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='is_dwg_file_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawing',
            name='sub_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.subvolume'),
        ),
        migrations.AddField(
            model_name='drawingfile',
            name='dwg_file',
            field=models.FileField(null=True, upload_to=DrawingApp.models.upload_path),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='package_number',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='revision_version',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
