# Generated by Django 4.1.7 on 2025-03-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='personnel_number',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
