# Generated by Django 4.2.10 on 2024-03-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_user_is_download_drawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInOutLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('device_info', models.TextField(null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
