# Generated by Django 4.2.10 on 2024-03-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_loginoutlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('volume_id', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subvolume',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('sub_volume_no', models.FloatField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.volume')),
            ],
        ),
    ]
