# Generated by Django 4.2.10 on 2024-09-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0013_remove_user_is_design_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldDepartment',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('old_names', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('new_department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AuthApp.department')),
            ],
        ),
    ]
