# Generated by Django 4.1.7 on 2024-05-20 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('barcode_no', models.CharField(max_length=250, null=True)),
                ('is_product_type', models.BooleanField(default=True)),
                ('status', models.CharField(default='Used', max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=235)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('ucs_code', models.CharField(db_index=True, max_length=250, unique=True)),
                ('description', models.TextField(null=True)),
                ('description_sap', models.TextField(null=True)),
                ('min_threshold', models.IntegerField()),
                ('max_threshold', models.IntegerField(null=True)),
                ('net_quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('is_mutli_type_unit', models.BooleanField(default=False)),
                ('ved_category', models.CharField(choices=[('Vital', 'VITAL'), ('Essential', 'ESSENTIAL'), ('Desirable', 'DESIRABLE')], default='Vital', max_length=20)),
                ('lead_time', models.IntegerField(default=1, help_text='Lead time in days')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('rack_no', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('source', models.TextField(db_index=True)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=235)),
            ],
        ),
        migrations.CreateModel(
            name='StocksHistory',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('purpose', models.TextField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('is_stock_out', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.employees')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.stocks')),
            ],
        ),
    ]
