# Generated by Django 4.1.7 on 2024-05-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockshistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocks',
            name='barcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.barcodes'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.products'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.racks'),
        ),
        migrations.AddField(
            model_name='racks',
            name='barcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.barcodes'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.productcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.unit'),
        ),
    ]
