# Generated by Django 4.1.7 on 2024-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='email',
        ),
        migrations.AddField(
            model_name='employees',
            name='personnel_number',
            field=models.CharField(default='', max_length=240, unique=True),
            preserve_default=False,
        ),
    ]
