# Generated by Django 4.2.10 on 2024-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_download_drawing',
            field=models.BooleanField(default=True),
        ),
    ]
