# Generated by Django 4.1.7 on 2024-05-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='employee_id',
        ),
    ]
