# Generated by Django 4.2.10 on 2024-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0006_user_is_view_manual_user_is_view_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvolume',
            name='sub_volume_no',
            field=models.CharField(max_length=10),
        ),
    ]
