# Generated by Django 4.2.10 on 2024-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0010_user_is_design_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personnel_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
