# Generated by Django 4.2.10 on 2024-03-18 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DrawingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('action_time', models.DateTimeField(default=datetime.datetime.now)),
                ('drawing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DrawingApp.drawing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
