# Generated by Django 4.2.10 on 2024-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0004_remove_drawing_volume_drawing_archive_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='drawing_file_type',
            field=models.CharField(choices=[('TIF', 'TIF'), ('PDF', 'PDF')], default='TIF', max_length=20),
        ),
    ]
