# Generated by Django 4.2.10 on 2024-04-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0005_alter_drawing_drawing_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='work_order_no',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
