# Generated by Django 4.2.10 on 2024-04-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0007_rename_work_order_no_drawing_work_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='fdr_approve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='letter_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='letter_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='pdr_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='supplier_number',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_type',
            field=models.CharField(choices=[('PDR', 'PDR'), ('CDBR', 'CDBR'), ('RS', 'RS'), ('PS', 'PS'), ('FDR', 'FDR'), ('MISCELLANEOUS', 'MISCELLANEOUS')], default='PDR', max_length=20),
        ),
    ]
