# Generated by Django 4.2.10 on 2024-04-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0009_remove_drawing_letter_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='date_of_registration',
            field=models.DateField(null=True),
        ),
    ]
