# Generated by Django 4.2.10 on 2024-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0007_document_documentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlog',
            name='status',
            field=models.CharField(choices=[('View Document', 'VIEW'), ('Add Document', 'ADD'), ('Update Document', 'UPDATE'), ('Archive Document', 'ARCHIVE'), ('Delete Document', 'DELETE')], default='View Document', max_length=20),
        ),
    ]
