# Generated by Django 4.2.10 on 2024-08-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIApp', '0009_sir_agency_stabilitycertification_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='unit',
        ),
    ]
