# Generated by Django 4.2.10 on 2024-04-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthApp', '0004_volume_subvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('standard_type', models.CharField(choices=[('BIS', 'BIS'), ('ASTM', 'ASTM'), ('AWWA', 'AWWA'), ('BRITISH', 'BRITISH'), ('DIN(GERMAN)', 'DIN(GERMAN)'), ('GOST(RUSSIAN)', 'GOST(RUSSIAN)'), ('IEC', 'IEC'), ('ISO', 'ISO'), ('IRST', 'IRST'), ('API', 'API'), ('PSN', 'PSN'), ('RSN', 'RSN'), ('IPSS', 'IPSS')], default='GOST(RUSSIAN)', max_length=100)),
                ('standard_no', models.CharField(db_index=True, max_length=100)),
                ('part_no', models.CharField(max_length=100, null=True)),
                ('section_no', models.CharField(max_length=100, null=True)),
                ('document_year', models.DateField(null=True)),
                ('division', models.CharField(max_length=100, null=True)),
                ('division_code', models.CharField(max_length=100, null=True)),
                ('committee_code', models.CharField(max_length=100, null=True)),
                ('committee_title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('upload_file', models.FileField(null=True, upload_to='standard/')),
                ('group', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('no_of_sheet', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_of_standard', models.CharField(max_length=100, null=True)),
                ('file_availability', models.BooleanField(null=True)),
                ('sub_volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthApp.subvolume')),
            ],
        ),
    ]
