# Generated by Django 4.2.10 on 2024-04-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSNVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_no', models.CharField(max_length=100)),
                ('volume_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RSNGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('rsn_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StandardApp.rsnvolume')),
            ],
        ),
    ]
