# Generated by Django 4.2.10 on 2024-04-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0005_alter_rsngroup_group_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsngroup',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
