# Generated by Django 4.2.10 on 2024-04-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0006_alter_rsngroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPSSTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
