# Generated by Django 4.2.10 on 2024-04-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0009_remove_standard_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsngroup',
            name='group_no',
        ),
    ]
