# Generated by Django 4.2.10 on 2024-04-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0011_rsnvolume_volume_id_alter_ipsstitle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='sub_volume',
        ),
        migrations.AddField(
            model_name='standard',
            name='rsn_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StandardApp.rsnvolume'),
        ),
    ]
