# Generated by Django 4.2.10 on 2024-04-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0012_remove_standard_sub_volume_standard_rsn_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StandardApp.rsngroup'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='rsn_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StandardApp.rsnvolume'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StandardApp.ipsstitle'),
        ),
    ]
