# Generated by Django 4.2.10 on 2024-04-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0015_standard_created_at_standard_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='archive_reason',
            field=models.TextField(null=True),
        ),
    ]
