# Generated by Django 4.2.10 on 2024-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0016_standard_archive_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardlog',
            name='status',
            field=models.CharField(choices=[('View Standard', 'VIEW'), ('Add Standard', 'ADD'), ('Update Standard', 'UPDATE'), ('Archive Standard', 'ARCHIVE'), ('Delete Standard', 'DELETE')], default='View Standard', max_length=20),
        ),
    ]
