# Generated by Django 4.2.10 on 2024-04-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0017_alter_standardlog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsnvolume',
            name='volume_id',
        ),
    ]
