# Generated by Django 4.2.10 on 2024-04-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StandardApp', '0018_remove_rsnvolume_volume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsngroup',
            name='group_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
