# Generated by Django 4.2.10 on 2024-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0002_alter_notice_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
