# Generated by Django 4.2.10 on 2024-04-19 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0005_alter_notice_description_alter_notice_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserRequest',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('personnel_number', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('cost_code_department', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
