# Generated by Django 4.2.10 on 2024-06-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeApp', '0006_newuserrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='notice',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
    ]
