# Generated by Django 4.2.10 on 2024-03-15 18:24

import DrawingApp.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('default_description', models.TextField(null=True)),
                ('drawing_type', models.CharField(choices=[('PDR', 'PDR'), ('CDBR', 'CDBR'), ('RS', 'RS'), ('PS', 'PS')], default='PDR', max_length=20)),
                ('drawing_number', models.IntegerField(db_index=True)),
                ('volume', models.CharField(choices=[('1.0', '1.0'), ('1.1', '1.1'), ('1.2', '1.2')], default='1.0', max_length=20, null=True)),
                ('supplier_name', models.CharField(db_index=True, max_length=250, null=True)),
                ('vendor_number', models.CharField(db_index=True, max_length=250, null=True)),
                ('client_number', models.CharField(db_index=True, max_length=250, null=True)),
                ('package_number', models.IntegerField(db_index=True, null=True)),
                ('revision_version', models.IntegerField(default=1)),
                ('drawing_size', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4')], default='A0', max_length=20)),
                ('drawing_file_type', models.CharField(choices=[('TIF', 'TIF'), ('PDF', 'PDF'), ('DWG', 'DWG')], default='TIF', max_length=20)),
                ('is_layout', models.BooleanField(default=False)),
                ('date_of_registration', models.DateField()),
                ('certification', models.CharField(max_length=220)),
                ('is_file_present', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('no_of_sheet', models.IntegerField(default=1)),
                ('remarks', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.department')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthApp.unit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=DrawingApp.models.upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('view_pdf_file', models.FileField(null=True, upload_to=DrawingApp.models.upload_path)),
                ('file_size', models.BigIntegerField()),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='DrawingApp.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingDescription',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('description', models.TextField(db_index=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='DrawingApp.drawing')),
                ('drawing_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawingfile', to='DrawingApp.drawingfile')),
            ],
        ),
    ]
