# Generated by Django 4.2.10 on 2024-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0002_drawinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawinglog',
            name='status',
            field=models.CharField(choices=[('View Drawing', 'VIEW'), ('Add Drawing', 'ADD'), ('Update Drawing', 'UPDATE'), ('Archive Drawing', 'ARCHIVE'), ('Download Drawing', 'DOWNLOAD')], default='View Drawing', max_length=20),
        ),
    ]
