# Generated by Django 4.2.10 on 2024-04-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0006_drawing_work_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='work_order_no',
            new_name='work_order_number',
        ),
    ]
