# Generated by Django 4.2.10 on 2024-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0012_rename_fdr_approve_date_drawing_fdr_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='drawing_type',
            field=models.CharField(choices=[('PDR', 'PDR'), ('CDBR', 'CDBR'), ('RS', 'RS'), ('PS', 'PS'), ('FDR', 'FDR'), ('MISC', 'MISC')], default='PDR', max_length=20),
        ),
    ]
