# Generated by Django 4.2.10 on 2024-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0014_alter_drawinglog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='revision_version',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
