# Generated by Django 4.2.10 on 2024-05-27 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0015_alter_drawing_revision_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='drawing_file_type',
            field=models.CharField(choices=[('TIF', 'TIF'), ('PDF', 'PDF')], db_index=True, default='TIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_type',
            field=models.CharField(choices=[('PDR', 'PDR'), ('CDBR', 'CDBR'), ('RS', 'RS'), ('PS', 'PS'), ('FDR', 'FDR'), ('MISC', 'MISC')], db_index=True, default='PDR', max_length=20),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='is_archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='is_file_present',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='is_layout',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='remarks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drawingdescription',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drawingfile',
            name='file_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drawinglog',
            name='action_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='drawinglog',
            name='message',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drawinglog',
            name='status',
            field=models.CharField(choices=[('View Drawing', 'VIEW'), ('Add Drawing', 'ADD'), ('Update Drawing', 'UPDATE'), ('Archive Drawing', 'ARCHIVE'), ('Delete Drawing', 'DELETE'), ('Download Drawing', 'DOWNLOAD')], db_index=True, default='View Drawing', max_length=20),
        ),
    ]
