# Generated by Django 4.2.10 on 2024-05-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0016_alter_drawing_drawing_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
