# Generated by Django 4.2.10 on 2024-08-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrawingApp', '0018_drawing_drawing_number_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawinglog',
            name='drawing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='DrawingApp.drawing'),
        ),
    ]
